ja: 
  helpers:
    submit:
        create: '登録する'
        update: '更新する'
        submit: '保存する'
  CustomFormBuilder:
    required:
        html: '<abbr class="nec">必須</abbr>'
    labels:
      user:
        name: '名前'
        email: 'メールアドレス'
        subject: '専門教科'
        password: 'パスワード'
    hints:
      user:
        email: 'サインインするメールアドレスを入力してください'
        password: '半角英数字のみ使えます'
    placeholders:
      user:
        name: '例）先生太郎'
        email: 'メールアドレス'
        subject: '社会,国語,数学,理科,英語'
        password: 'パスワード'